/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MonecoProtocol {
  export type ImagePoolStruct = {
    imageHash: BytesLike;
    collector: AddressLike;
    latitude: BigNumberish;
    longitude: BigNumberish;
    poolReward: BigNumberish;
    validatorCount: BigNumberish;
    approveVotes: BigNumberish;
    rejectVotes: BigNumberish;
    status: BigNumberish;
    submittedAt: BigNumberish;
    rewardDistributed: boolean;
    locationName: string;
    difficulty: BigNumberish;
  };

  export type ImagePoolStructOutput = [
    imageHash: string,
    collector: string,
    latitude: bigint,
    longitude: bigint,
    poolReward: bigint,
    validatorCount: bigint,
    approveVotes: bigint,
    rejectVotes: bigint,
    status: bigint,
    submittedAt: bigint,
    rewardDistributed: boolean,
    locationName: string,
    difficulty: bigint
  ] & {
    imageHash: string;
    collector: string;
    latitude: bigint;
    longitude: bigint;
    poolReward: bigint;
    validatorCount: bigint;
    approveVotes: bigint;
    rejectVotes: bigint;
    status: bigint;
    submittedAt: bigint;
    rewardDistributed: boolean;
    locationName: string;
    difficulty: bigint;
  };

  export type UserStruct = {
    role: BigNumberish;
    level: BigNumberish;
    correctAnswers: BigNumberish;
    stakedAmount: BigNumberish;
    isSlashed: boolean;
    totalEarned: BigNumberish;
  };

  export type UserStructOutput = [
    role: bigint,
    level: bigint,
    correctAnswers: bigint,
    stakedAmount: bigint,
    isSlashed: boolean,
    totalEarned: bigint
  ] & {
    role: bigint;
    level: bigint;
    correctAnswers: bigint;
    stakedAmount: bigint;
    isSlashed: boolean;
    totalEarned: bigint;
  };
}

export interface MonecoProtocolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COLLECTOR_SHARE"
      | "COLLECTOR_STAKE"
      | "DIFFICULTY_REWARDS"
      | "LEVEL_BONUS_BPS"
      | "LEVEL_THRESHOLDS"
      | "MAX_WRONG_VOTES"
      | "VALIDATOR_SHARE"
      | "aiOracleCallback"
      | "allPools"
      | "approvalQuorum"
      | "calculateUserReward"
      | "castValidationVote"
      | "createMunicipalPool"
      | "fundProtocol"
      | "getAllPools"
      | "getNextLevelInfo"
      | "getPoolCount"
      | "getPoolInfo"
      | "getUserInfo"
      | "imagePools"
      | "owner"
      | "poolCollectors"
      | "poolValidators"
      | "registerAsCollector"
      | "registerAsValidator"
      | "renounceOwnership"
      | "setApprovalQuorum"
      | "setValidatorThreshold"
      | "submitImage"
      | "token"
      | "transferOwnership"
      | "users"
      | "validationVotes"
      | "validatorThreshold"
      | "validatorWrongAnswers"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AICheckFailed"
      | "AICheckPassed"
      | "CollectorSlashed"
      | "CollectorStaked"
      | "ImageSubmitted"
      | "LevelUp"
      | "MunicipalPoolCreated"
      | "OwnershipTransferred"
      | "PoolFinalized"
      | "RewardDistributed"
      | "UserRegistered"
      | "ValidationVoteCast"
      | "ValidatorBanned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COLLECTOR_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COLLECTOR_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DIFFICULTY_REWARDS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "LEVEL_BONUS_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LEVEL_THRESHOLDS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_WRONG_VOTES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VALIDATOR_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aiOracleCallback",
    values: [BytesLike, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "allPools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approvalQuorum",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateUserReward",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castValidationVote",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "createMunicipalPool",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundProtocol",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNextLevelInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "imagePools",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolCollectors",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "poolValidators",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAsCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAsValidator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalQuorum",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setValidatorThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitImage",
    values: [BytesLike, BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "validationVotes",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validatorThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validatorWrongAnswers",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "COLLECTOR_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COLLECTOR_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DIFFICULTY_REWARDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LEVEL_BONUS_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LEVEL_THRESHOLDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_WRONG_VOTES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VALIDATOR_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aiOracleCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allPools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approvalQuorum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateUserReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castValidationVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMunicipalPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextLevelInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "imagePools", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolCollectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAsCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAsValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalQuorum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setValidatorThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitImage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validationVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorWrongAnswers",
    data: BytesLike
  ): Result;
}

export namespace AICheckFailedEvent {
  export type InputTuple = [poolId: BytesLike, reason: string];
  export type OutputTuple = [poolId: string, reason: string];
  export interface OutputObject {
    poolId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AICheckPassedEvent {
  export type InputTuple = [poolId: BytesLike];
  export type OutputTuple = [poolId: string];
  export interface OutputObject {
    poolId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollectorSlashedEvent {
  export type InputTuple = [
    collector: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [collector: string, amount: bigint, reason: string];
  export interface OutputObject {
    collector: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollectorStakedEvent {
  export type InputTuple = [collector: AddressLike, amount: BigNumberish];
  export type OutputTuple = [collector: string, amount: bigint];
  export interface OutputObject {
    collector: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ImageSubmittedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    collector: AddressLike,
    locationName: string
  ];
  export type OutputTuple = [
    poolId: string,
    collector: string,
    locationName: string
  ];
  export interface OutputObject {
    poolId: string;
    collector: string;
    locationName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LevelUpEvent {
  export type InputTuple = [user: AddressLike, newLevel: BigNumberish];
  export type OutputTuple = [user: string, newLevel: bigint];
  export interface OutputObject {
    user: string;
    newLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MunicipalPoolCreatedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    locationName: string,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    locationName: string,
    reward: bigint
  ];
  export interface OutputObject {
    poolId: string;
    locationName: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolFinalizedEvent {
  export type InputTuple = [poolId: BytesLike, approved: boolean];
  export type OutputTuple = [poolId: string, approved: boolean];
  export interface OutputObject {
    poolId: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [poolId: string, recipient: string, amount: bigint];
  export interface OutputObject {
    poolId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [user: AddressLike, role: BigNumberish];
  export type OutputTuple = [user: string, role: bigint];
  export interface OutputObject {
    user: string;
    role: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidationVoteCastEvent {
  export type InputTuple = [
    poolId: BytesLike,
    validator: AddressLike,
    vote: boolean
  ];
  export type OutputTuple = [poolId: string, validator: string, vote: boolean];
  export interface OutputObject {
    poolId: string;
    validator: string;
    vote: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorBannedEvent {
  export type InputTuple = [validator: AddressLike];
  export type OutputTuple = [validator: string];
  export interface OutputObject {
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MonecoProtocol extends BaseContract {
  connect(runner?: ContractRunner | null): MonecoProtocol;
  waitForDeployment(): Promise<this>;

  interface: MonecoProtocolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COLLECTOR_SHARE: TypedContractMethod<[], [bigint], "view">;

  COLLECTOR_STAKE: TypedContractMethod<[], [bigint], "view">;

  DIFFICULTY_REWARDS: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  LEVEL_BONUS_BPS: TypedContractMethod<[], [bigint], "view">;

  LEVEL_THRESHOLDS: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  MAX_WRONG_VOTES: TypedContractMethod<[], [bigint], "view">;

  VALIDATOR_SHARE: TypedContractMethod<[], [bigint], "view">;

  aiOracleCallback: TypedContractMethod<
    [poolId: BytesLike, passed: boolean, reason: string],
    [void],
    "nonpayable"
  >;

  allPools: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  approvalQuorum: TypedContractMethod<[], [bigint], "view">;

  calculateUserReward: TypedContractMethod<
    [userAddr: AddressLike, baseAmount: BigNumberish],
    [bigint],
    "view"
  >;

  castValidationVote: TypedContractMethod<
    [poolId: BytesLike, approve: boolean],
    [void],
    "nonpayable"
  >;

  createMunicipalPool: TypedContractMethod<
    [
      locationName: string,
      latitude: BigNumberish,
      longitude: BigNumberish,
      rewardAmount: BigNumberish,
      difficulty: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  fundProtocol: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllPools: TypedContractMethod<[], [string[]], "view">;

  getNextLevelInfo: TypedContractMethod<
    [userAddr: AddressLike],
    [
      [bigint, bigint, bigint] & {
        threshold: bigint;
        progress: bigint;
        remaining: bigint;
      }
    ],
    "view"
  >;

  getPoolCount: TypedContractMethod<[], [bigint], "view">;

  getPoolInfo: TypedContractMethod<
    [poolId: BytesLike],
    [MonecoProtocol.ImagePoolStructOutput],
    "view"
  >;

  getUserInfo: TypedContractMethod<
    [userAddr: AddressLike],
    [MonecoProtocol.UserStructOutput],
    "view"
  >;

  imagePools: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        bigint
      ] & {
        imageHash: string;
        collector: string;
        latitude: bigint;
        longitude: bigint;
        poolReward: bigint;
        validatorCount: bigint;
        approveVotes: bigint;
        rejectVotes: bigint;
        status: bigint;
        submittedAt: bigint;
        rewardDistributed: boolean;
        locationName: string;
        difficulty: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  poolCollectors: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  poolValidators: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  registerAsCollector: TypedContractMethod<[], [void], "nonpayable">;

  registerAsValidator: TypedContractMethod<[], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setApprovalQuorum: TypedContractMethod<
    [_quorum: BigNumberish],
    [void],
    "nonpayable"
  >;

  setValidatorThreshold: TypedContractMethod<
    [_threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitImage: TypedContractMethod<
    [
      imageHash: BytesLike,
      latitude: BigNumberish,
      longitude: BigNumberish,
      locationName: string,
      difficulty: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        role: bigint;
        level: bigint;
        correctAnswers: bigint;
        stakedAmount: bigint;
        isSlashed: boolean;
        totalEarned: bigint;
      }
    ],
    "view"
  >;

  validationVotes: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [[boolean, bigint] & { vote: boolean; timestamp: bigint }],
    "view"
  >;

  validatorThreshold: TypedContractMethod<[], [bigint], "view">;

  validatorWrongAnswers: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COLLECTOR_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COLLECTOR_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DIFFICULTY_REWARDS"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "LEVEL_BONUS_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LEVEL_THRESHOLDS"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_WRONG_VOTES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VALIDATOR_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "aiOracleCallback"
  ): TypedContractMethod<
    [poolId: BytesLike, passed: boolean, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allPools"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "approvalQuorum"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateUserReward"
  ): TypedContractMethod<
    [userAddr: AddressLike, baseAmount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "castValidationVote"
  ): TypedContractMethod<
    [poolId: BytesLike, approve: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createMunicipalPool"
  ): TypedContractMethod<
    [
      locationName: string,
      latitude: BigNumberish,
      longitude: BigNumberish,
      rewardAmount: BigNumberish,
      difficulty: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundProtocol"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllPools"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getNextLevelInfo"
  ): TypedContractMethod<
    [userAddr: AddressLike],
    [
      [bigint, bigint, bigint] & {
        threshold: bigint;
        progress: bigint;
        remaining: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPoolInfo"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [MonecoProtocol.ImagePoolStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserInfo"
  ): TypedContractMethod<
    [userAddr: AddressLike],
    [MonecoProtocol.UserStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "imagePools"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        bigint
      ] & {
        imageHash: string;
        collector: string;
        latitude: bigint;
        longitude: bigint;
        poolReward: bigint;
        validatorCount: bigint;
        approveVotes: bigint;
        rejectVotes: bigint;
        status: bigint;
        submittedAt: bigint;
        rewardDistributed: boolean;
        locationName: string;
        difficulty: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolCollectors"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolValidators"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAsCollector"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerAsValidator"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setApprovalQuorum"
  ): TypedContractMethod<[_quorum: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setValidatorThreshold"
  ): TypedContractMethod<[_threshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitImage"
  ): TypedContractMethod<
    [
      imageHash: BytesLike,
      latitude: BigNumberish,
      longitude: BigNumberish,
      locationName: string,
      difficulty: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        role: bigint;
        level: bigint;
        correctAnswers: bigint;
        stakedAmount: bigint;
        isSlashed: boolean;
        totalEarned: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "validationVotes"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [[boolean, bigint] & { vote: boolean; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "validatorThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "validatorWrongAnswers"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "AICheckFailed"
  ): TypedContractEvent<
    AICheckFailedEvent.InputTuple,
    AICheckFailedEvent.OutputTuple,
    AICheckFailedEvent.OutputObject
  >;
  getEvent(
    key: "AICheckPassed"
  ): TypedContractEvent<
    AICheckPassedEvent.InputTuple,
    AICheckPassedEvent.OutputTuple,
    AICheckPassedEvent.OutputObject
  >;
  getEvent(
    key: "CollectorSlashed"
  ): TypedContractEvent<
    CollectorSlashedEvent.InputTuple,
    CollectorSlashedEvent.OutputTuple,
    CollectorSlashedEvent.OutputObject
  >;
  getEvent(
    key: "CollectorStaked"
  ): TypedContractEvent<
    CollectorStakedEvent.InputTuple,
    CollectorStakedEvent.OutputTuple,
    CollectorStakedEvent.OutputObject
  >;
  getEvent(
    key: "ImageSubmitted"
  ): TypedContractEvent<
    ImageSubmittedEvent.InputTuple,
    ImageSubmittedEvent.OutputTuple,
    ImageSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "LevelUp"
  ): TypedContractEvent<
    LevelUpEvent.InputTuple,
    LevelUpEvent.OutputTuple,
    LevelUpEvent.OutputObject
  >;
  getEvent(
    key: "MunicipalPoolCreated"
  ): TypedContractEvent<
    MunicipalPoolCreatedEvent.InputTuple,
    MunicipalPoolCreatedEvent.OutputTuple,
    MunicipalPoolCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolFinalized"
  ): TypedContractEvent<
    PoolFinalizedEvent.InputTuple,
    PoolFinalizedEvent.OutputTuple,
    PoolFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ValidationVoteCast"
  ): TypedContractEvent<
    ValidationVoteCastEvent.InputTuple,
    ValidationVoteCastEvent.OutputTuple,
    ValidationVoteCastEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorBanned"
  ): TypedContractEvent<
    ValidatorBannedEvent.InputTuple,
    ValidatorBannedEvent.OutputTuple,
    ValidatorBannedEvent.OutputObject
  >;

  filters: {
    "AICheckFailed(bytes32,string)": TypedContractEvent<
      AICheckFailedEvent.InputTuple,
      AICheckFailedEvent.OutputTuple,
      AICheckFailedEvent.OutputObject
    >;
    AICheckFailed: TypedContractEvent<
      AICheckFailedEvent.InputTuple,
      AICheckFailedEvent.OutputTuple,
      AICheckFailedEvent.OutputObject
    >;

    "AICheckPassed(bytes32)": TypedContractEvent<
      AICheckPassedEvent.InputTuple,
      AICheckPassedEvent.OutputTuple,
      AICheckPassedEvent.OutputObject
    >;
    AICheckPassed: TypedContractEvent<
      AICheckPassedEvent.InputTuple,
      AICheckPassedEvent.OutputTuple,
      AICheckPassedEvent.OutputObject
    >;

    "CollectorSlashed(address,uint256,string)": TypedContractEvent<
      CollectorSlashedEvent.InputTuple,
      CollectorSlashedEvent.OutputTuple,
      CollectorSlashedEvent.OutputObject
    >;
    CollectorSlashed: TypedContractEvent<
      CollectorSlashedEvent.InputTuple,
      CollectorSlashedEvent.OutputTuple,
      CollectorSlashedEvent.OutputObject
    >;

    "CollectorStaked(address,uint256)": TypedContractEvent<
      CollectorStakedEvent.InputTuple,
      CollectorStakedEvent.OutputTuple,
      CollectorStakedEvent.OutputObject
    >;
    CollectorStaked: TypedContractEvent<
      CollectorStakedEvent.InputTuple,
      CollectorStakedEvent.OutputTuple,
      CollectorStakedEvent.OutputObject
    >;

    "ImageSubmitted(bytes32,address,string)": TypedContractEvent<
      ImageSubmittedEvent.InputTuple,
      ImageSubmittedEvent.OutputTuple,
      ImageSubmittedEvent.OutputObject
    >;
    ImageSubmitted: TypedContractEvent<
      ImageSubmittedEvent.InputTuple,
      ImageSubmittedEvent.OutputTuple,
      ImageSubmittedEvent.OutputObject
    >;

    "LevelUp(address,uint8)": TypedContractEvent<
      LevelUpEvent.InputTuple,
      LevelUpEvent.OutputTuple,
      LevelUpEvent.OutputObject
    >;
    LevelUp: TypedContractEvent<
      LevelUpEvent.InputTuple,
      LevelUpEvent.OutputTuple,
      LevelUpEvent.OutputObject
    >;

    "MunicipalPoolCreated(bytes32,string,uint256)": TypedContractEvent<
      MunicipalPoolCreatedEvent.InputTuple,
      MunicipalPoolCreatedEvent.OutputTuple,
      MunicipalPoolCreatedEvent.OutputObject
    >;
    MunicipalPoolCreated: TypedContractEvent<
      MunicipalPoolCreatedEvent.InputTuple,
      MunicipalPoolCreatedEvent.OutputTuple,
      MunicipalPoolCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolFinalized(bytes32,bool)": TypedContractEvent<
      PoolFinalizedEvent.InputTuple,
      PoolFinalizedEvent.OutputTuple,
      PoolFinalizedEvent.OutputObject
    >;
    PoolFinalized: TypedContractEvent<
      PoolFinalizedEvent.InputTuple,
      PoolFinalizedEvent.OutputTuple,
      PoolFinalizedEvent.OutputObject
    >;

    "RewardDistributed(bytes32,address,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;

    "UserRegistered(address,uint8)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;

    "ValidationVoteCast(bytes32,address,bool)": TypedContractEvent<
      ValidationVoteCastEvent.InputTuple,
      ValidationVoteCastEvent.OutputTuple,
      ValidationVoteCastEvent.OutputObject
    >;
    ValidationVoteCast: TypedContractEvent<
      ValidationVoteCastEvent.InputTuple,
      ValidationVoteCastEvent.OutputTuple,
      ValidationVoteCastEvent.OutputObject
    >;

    "ValidatorBanned(address)": TypedContractEvent<
      ValidatorBannedEvent.InputTuple,
      ValidatorBannedEvent.OutputTuple,
      ValidatorBannedEvent.OutputObject
    >;
    ValidatorBanned: TypedContractEvent<
      ValidatorBannedEvent.InputTuple,
      ValidatorBannedEvent.OutputTuple,
      ValidatorBannedEvent.OutputObject
    >;
  };
}
