/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MonecoProtocol__factory } from "./MonecoProtocol__factory";
export { MonecoToken__factory } from "./MonecoToken__factory";
